### ISSUE TITLE
Failed reading phenotypes file

### ISSUE THREAD

**Issue by frucelee** [cozygene/permutation-testing#6]
Dear, 
  Thank you for the perfect software. It reported to me that failed reading phenotypes file when I used this software. 
Traceback (most recent call last):
  File "./permutation_testing.py", line 455, in <module>
    phenotypes = loadtxt(args.phenotypes)
  File "/home/lee/miniconda3/lib/python3.8/site-packages/numpy/lib/npyio.py", line 1146, in loadtxt
    for x in read_data(_loadtxt_chunksize):
  File "/home/lee/miniconda3/lib/python3.8/site-packages/numpy/lib/npyio.py", line 997, in read_data
    items = [conv(val) for (conv, val) in zip(converters, vals)]
  File "/home/lee/miniconda3/lib/python3.8/site-packages/numpy/lib/npyio.py", line 997, in <listcomp>
    items = [conv(val) for (conv, val) in zip(converters, vals)]
  File "/home/lee/miniconda3/lib/python3.8/site-packages/numpy/lib/npyio.py", line 734, in floatconv
    return float(x)
ValueError: could not convert string to float: 'NA'

Was it the problem due to existing of the NA value? However, at some time, there was some missing value in our dataset. Do you know how to deal with it?
Best,
Lee

**Comment by regevs** [comment]
Thank you for your interest in the method.

The method cannot (and shouldn't) handle missing values. I recommend
removing the missing samples before proceeding.
